version: '3.8'

services:
  url-shortener:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - DB_PATH=/app/data/urls.db
    restart: unless-stopped